### ISSUE TITLE
Detailed Installation Guide

### ISSUE THREAD

**Issue by LYS1THEA** [royvds/assDialogueMerger#1]
Can you please provide a detailed installation guide? I installed `python 3.9.11` and then installed the dependency via `pip` but this is what I get:
```cmd
Microsoft Windows [Version 10.0.22000.856]
(c) Microsoft Corporation. All rights reserved.

C:\Users\username\Downloads\GitHub\assDialogueMerger\assdialoguemerger>assdialoguemerger.py --help

C:\Users\username\Downloads\GitHub\assDialogueMerger\assdialoguemerger>
```

**Comment by rosvob** [comment]
For now you can install it with:
```console
pip install .
```
inside the root folder (i.e. assDialogueMerger, not the subfolder assdialoguemerger).
then you can use it as "assdialoguemerger" without .py from wherever you want.
I will upload this repo to pypi for easier installation and update the README.
